trigger:
- main

name: middleware-$(Build.BuildId)

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: PackageAndBuild
    steps:
    - checkout: self
      fetchDepth: 1
      clean: true
      persistCredentials: true
    - task: CmdLine@2
      displayName: Fetch additional repos
      inputs:
        script: |
          git clone https://$(GIT_USER):$(PAT)@github.com/From-pets-to-pals/petpals-common.git
          git clone https://$(GIT_USER):$(PAT)@github.com/From-pets-to-pals/petpals-conf.git
          ls
          cp -r petpals-conf/dev/middleware/resources $(APP_NAME)/src/main
          ls $(APP_NAME)/src/main/resources
          cat petpals-conf/dev/middleware/resources/application.properties
    - task: CmdLine@2
      displayName: Download Maven
      inputs:
        script: 'wget https://archive.apache.org/dist/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip'
    - task: ExtractFiles@1
      displayName: Extract maven
      inputs:
        archiveFilePatterns: 'apache-maven-3.9.6-bin.zip'
        destinationFolder: '$(Build.SourcesDirectory)/maven'
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Maven@3
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/petpals-common/petpals-common/pom.xml'
        goals: 'clean install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Path'
        mavenDirectory: '$(Build.SourcesDirectory)/maven/apache-maven-3.9.6'
        mavenSetM2Home: true
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Maven@4
      displayName: Compile, Test, Build Jar
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/$(APP_NAME)/pom.xml'
        goals: 'clean package'
        options: '-DSECRET=$(SECRET) -DTENANT-ID=$(TENANT-ID) -DCLIENT-ID=$(CLIENT-ID) -DPUBLIC-KEY=$(PUBLIC-KEY) -DPRIVATE-KEY=$(PRIVATE-KEY) -DVAULT=$(VAULT)'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Path'
        mavenDirectory: '$(Build.SourcesDirectory)/maven/apache-maven-3.9.6'
        mavenSetM2Home: true
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
   
    - task: PublishCodeCoverageResults@2
      inputs:
        summaryFileLocation: '$(Build.SourcesDirectory)/$(APP_NAME)/target/jacoco-report/jacoco.xml'
        failIfCoverageEmpty: true
    - task: Maven@4
      displayName: Run Sonar Analysis
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/$(APP_NAME)/pom.xml'
        goals: 'sonar:sonar'
        options: '-Dsonar.token=$(SONAR_TOKEN) -Dsonar.qualitygate.wait=true'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Path'
        mavenDirectory: '$(Build.SourcesDirectory)/maven/apache-maven-3.9.6'
        mavenSetM2Home: true
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/$(APP_NAME)/target'
        Contents: '$(APP_NAME)-runner.jar'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(APP_NAME)'
        publishLocation: 'Container'