pool:
  vmImage: ubuntu-latest
name: middleware-$(Build.BuildId)
stages:
- stage: Deploy
  displayName: Deploy to petpals-middleware
  jobs:
  - job: Deploy
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'specific'
        project: '12e6b272-e75b-4b73-aebc-da22ad6551a2'
        pipeline: '16'
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        artifactName: '$(APP_NAME)'
        itemPattern: '**/*.jar'
        downloadPath: '$(System.ArtifactsDirectory)'
        checkDownloadedFiles: true
    - task: CopyFiles@2
      displayName: 'Copy Files from artifact staging directory'
      inputs:
        SourceFolder: '$(System.ArtifactsDirectory)/$(APP_NAME)'
        Contents: '$(APP_NAME)-runner.jar'
        TargetFolder: '$(System.DefaultWorkingDirectory)'
        CleanTargetFolder: true
        OverWrite: true
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Azure subscription 1(1)(f1248dd5-2384-4478-bf73-b940c14b63dc)'
        appType: 'webAppLinux'
        appName: 'petpals-middleware-dev'
        package: '$(System.DefaultWorkingDirectory)/$(APP_NAME)-runner.jar'
        runtimeStack: 'JAVA|17-java17'
        startUpCommand: 'java -DSECRET=$(SECRET) -Dquarkus.profile=prod -DTENANT-ID=$(TENANT-ID) -DCLIENT-ID=$(CLIENT-ID) -DVAULT=$(VAULT) -DPUBLIC-KEY=$(PUBLIC-KEY) -DPRIVATE-KEY=$(PRIVATE-KEY) -jar /home/site/wwwroot/$(APP_NAME)-runner.jar'
        appSettings: '-WEBSITES_PORT 80'
        configurationStrings: '-PORT 80'
